baseurl = "https://wobblybrian.xyz"
languageCode = "en-ie"
title = "wobbly brian"

[params]
description = "My website"

[outputs]
home = "HTML"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 2

[[menu.social]]
name = "Bluesky"
url = "https://bsky.app/profile/did:plc:waj6pke4gnh3qsjujzhp6ehn"
weight = 1

[[menu.social]]
name = "GitHub"
url = "https://github.com/wobblybrian"
weight = 2

[[menu.social]]
name = "YouTube"
url = "https://youtube.com/@wobblybrian"
weight = 3

[[menu.social]]
name = "Instagram"
url = "https://instagram.com/wobbly.brian"
weight = 4

[[menu.social]]
name = "Reddit"
url = "https://reddit.com/user/wobblybrian"
weight = 5

[[menu.social]]
name = "Mastodon"
url = "https://mastodon.social/@wobblybrian"
weight = 6

[[menu.social]]
name = "SoundCloud"
url = "https://soundcloud.com/wobblybrian"
weight = 7

[markup]
  [markup.goldmark.extensions]
    [markup.goldmark.extensions.extras.superscript]
          enable = true
    [markup.goldmark.parser]
          wrapStandAloneImageWithinParagraph = false