name = "xyz"
compatibility_date = "2025-07-11"

routes = [
  { pattern = "wobblybrian.xyz", custom_domain = true },
  { pattern = "www.wobblybrian.xyz", custom_domain = true },
]

[assets]
directory = "./public"
not_found_handling = "404-page"